global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'thread-performance-monitor'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # Spring Boot Application - Platform Threads
  - job_name: 'spring-boot-platform'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          thread_type: 'platform'
          service: 'thread-demo'
          environment: 'test'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'jvm_.*|http_.*|tomcat_.*|system_.*|process_.*|hikaricp_.*'
        action: keep

  # Spring Boot Application - Virtual Threads (for future use)
  - job_name: 'spring-boot-virtual'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          thread_type: 'virtual'
          service: 'thread-demo'
          environment: 'test'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'jvm_.*|http_.*|tomcat_.*|system_.*|process_.*|hikaricp_.*'
        action: keep